### Admin CMS APIs

### Root API
GET http://localhost:8001/

### Create new admin
POST http://localhost:8001/api/v1/admin
Content-Type: application/json

{
    "fname":"Bijay",
    "lname":"Nagarkoti",
    "email":"a@gmail.com",
    "dob":"12-12-2829",
    "password":"ASDFJKL;",
    "phone":"8383838383",
    "address":"Sydney",
    "gender":"male"
}

 
#category router
### get all or single category  

GET  http://localhost:8001/api/v1/category/




### Post new category 
POST  http://localhost:8001/api/v1/category
Content-Type: application/json

{
    "name":"furniture",
    "parentCat" : "62b7b0d2547f4fc3156ce8e0"
    

}
### update category 
PATCH   http://localhost:8001/api/v1/category
Content-Type: application/json

{
    "_id" : "62b7b134547f4fc3156ce8e3",
    "name":"Kitchens",
    "parentCat" : null
    

}



### Delete category 
DELETE http://localhost:8001/api/v1/category/62aea713ea91489005fa6937


